# This rule is not used by the project visitors-helm-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to example.trieubui1012.com resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: visitors-helm-operator
    app.kubernetes.io/managed-by: kustomize
  name: visitorapp-viewer-role
rules:
- apiGroups:
  - example.trieubui1012.com
  resources:
  - visitorapps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - example.trieubui1012.com
  resources:
  - visitorapps/status
  verbs:
  - get
